amends for armv6

diff --git a/buildraw b/buildraw
--- a/buildraw
+++ b/buildraw
@@ -15,18 +15,30 @@ Usage: buildraw [-n] [-h]"
 EOM
 }
 
-function install_dependencies() 
+function install_node()
 {
-    git pull || perr_and_exit "Failed to pull latest firewalla code."
+    echo "Installing node source repository..."
+    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
+    export NVM_DIR="$HOME/.nvm"
+    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
+    #[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+    export PATH=$PATH:/sbin
+    nvm install --lts
+}
+
+function install_dependencies()
+{
+    # git pull || perr_and_exit "Failed to pull latest firewalla code."
 
     # TODO: check local apt mirror
-    echo "Installing node source repository..."
-    sudo  curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -   || perr_and_exit "Failed to install node source repo"
+    if ! [ -x "$(command -v nodejs 2>/dev/null)" ]; then
+        install_node || perr_and_exit "Failed to install node."
+    fi
 
     echo "Executing apt-get update, please be patient..."
-    sudo apt-get update   || perr_and_exit "apt-get update failed."
+    sudo apt-get update || perr_and_exit "apt-get update failed."
 
-    apt_pkg_list="net-tools curl redis-server iptables ca-certificates nmap dsniff bluetooth bluez libbluetooth-dev libudev-dev nodejs openvpn easy-rsa python-pip cron"
+    apt_pkg_list="net-tools curl redis-server iptables ca-certificates nmap dsniff bluetooth bluez libbluetooth-dev libudev-dev openvpn easy-rsa python-pip cron bro"
 
     echo "Installing dependencies, please be patient..."
     sudo apt-get install $apt_pkg_list -y || perr_and_exit "Failed to install needed packages."
@@ -38,8 +50,8 @@ function install_dependencies()
         sudo npm config set unsafe-perm true
     fi
     echo "Installing tools: forever and xml-json..."
-    sudo npm install forever -g 
-    sudo npm install xml-json -g 
+    sudo npm install forever -g
+    sudo npm install xml-json -g
 
     echo "Setting up required folders and configures..."
     sudo mkdir -p /blog || perr_and_exit "Failed to create folder /blog"
@@ -70,23 +82,15 @@ function install_walla()
         cd $FW_NODE_MODULES_PATH
         git reset -q --hard `cat $FIREWALLA_HOME/scripts/NODE_MODULES_REVISION.$CPU_PLATFORM`
         cd -
+    else
+        cd $basedir && npm install || echo "[WARNING] There are errors during npm install."
+        cd $basedir/api && npm install ||  echo "[WARNING] There are errors during npm install."
     fi
 
     #no need to install npm any more, they are already provided by .node_modules
 #    cd $basedir && npm install || echo "[WARNING] There are errors during npm install."
 #    cd $basedir/api && npm install ||  echo "[WARNING] There are errors during npm install."
 
-    # Skip bro installation if in docker environment, bro in apt repo will be used in Docker
-    if [[ ! -f /.dockerenv ]]; then
-	echo "Installing bro..."
-	BRO_PKG="bro.tar.gz"
-	if [[ $CPU_PLATFORM == "x86_64" ]]; then
-            BRO_PKG="/home/$USER/.node_modules/bro.$CPU_PLATFORM.tar.gz"
-	fi
-	cd $basedir/imports && tar -zxf $BRO_PKG && sudo cp -r -f  $basedir/imports/bro /usr/local/ && rm -r -f $basedir/imports/bro || perr_and_exit "Failed to install bro."
-	cp $basedir/bin/real/bit* $basedir/bin/ 
-    fi
-    
     sudo cp $basedir/etc/sysctl.conf /etc/sysctl.conf || perr_and_exit "Failed to replace system sysctl.conf."
     sudo cp $basedir/etc/bro-cron /etc/cron.hourly/. || perr_and_exit "Failed to install root bron cronjobs."
     crontab $basedir/etc/brotab || perr_and_exit "Failed to install user bro cronjobs."
